main: tk.shanebee.nbt.NBeeT
name: SK-NBeeT
version: 1.2.3
authors: [jaylawl, ShaneBee]
description: Provides NBT usages within Skript
website: https://github.com/ShaneBeee/Sk-NBeeT
api-version: 1.13
softdepend: [Skript]