main: tk.shanebee.nbt.NBeeT
name: SK-NBeeT
version: 2.11.1
authors: [jaylawl, ShaneBee]
description: Provides NBT usages within Skript
website: https://github.com/ShaneBeee/Sk-NBeeT
softdepend: [Skript]
api-version: '1.13'
