main: tk.shanebee.nbt.NBeeT
name: SK-NBeeT
version: 2.8.0-Beta1
authors: [jaylawl, ShaneBee]
description: Provides NBT usages within Skript
website: https://github.com/ShaneBeee/Sk-NBeeT
softdepend: [Skript]